---

UniquePatchingIdentifierScope: "net.devtools.meditation"

Hooking:
  NativeExportedEntryPointSymbol: "MeditationInitialize"
  ManagedBootstrapEntryPointTypeFullName: "Meditation.Bootstrap.Managed.EntryPoint"
  ManagedBootstrapEntryPointHookMethod: "Hook"
  ManagedBootstrapEntryPointUnhookMethod: "Unhook"

NativeExecutables:
  - Path: "Meditation.Bootstrap.Native.dll"
    Architecture: "X64"
    OperatingSystem: "Windows"
  - Path: "Meditation.Bootstrap.Native.so"
    Architecture: "X64"
    OperatingSystem: "Linux"

Logging:
  MainApplicationFileName: "%localappdata%/Meditation/Meditation.log"
  BootstrapNativeFileName: "%localappdata%/Meditation/Meditation.Bootstrap.Native.log"
  BootstrapManagedFileName: "%localappdata%/Meditation/Meditation.Bootstrap.Managed.log"